name:                glushkov-automata
version:             0.1.0.0
github:              "githubuser/glushkov-automata"
license:             BSD-3-Clause
author:              "Dot"
maintainer:          "example@example.com"
copyright:           "2024"

extra-source-files:
- README.md
- CHANGELOG.md

default-extensions:
- OverloadedStrings
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- ScopedTypeVariables
- OverloadedLabels
- QuasiQuotes
- DeriveGeneric
- MultiParamTypeClasses
- FlexibleInstances
- TypeFamilies
- FlexibleContexts
- TypeOperators
- InstanceSigs

description:         Please see the README on GitHub at <https://github.com/githubuser/glushkov-automata#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - array
  - base
  - text
  - containers
  - mtl
  - fgl
  - graphviz
  - aeson
  - bytestring
  build-tools:
  - alex
  - happy

executables:
  glushkov-automata-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glushkov-automata
    - haskell-gi-base
    - gi-gtk
    - gi-gdk
    - gi-gdkpixbuf
    - text
    - containers
    - graphviz
    - fgl
    - bytestring
    - gi-cairo
    - process
    - filepath
    - directory

tests:
  glushkov-automata-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glushkov-automata
    - QuickCheck
    - text

benchmarks:
  my-benchmark:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - glushkov-automata
    - criterion
    - random